### ISSUE TITLE
GoToAction can not be used when changing the airplane position

### ISSUE THREAD

**Issue by chinanewer** [dji-sdk/Mobile-SDK-Android#101] opened 2017-04-28 02:38 UTC
the GoToAction in TimelineElement ，it can not be used when changing the airplane position，But can only be used when changing height。

**Comment by DJI-RobertLiu** [comment] 2017-05-02 17:57
GoToAction has a known issue in the current release. It works fine at first GoToAction, but finishes immediately at second GoToAction without error.  The root cause on this issue has been fixed.  The fix will be available in next release. 
It is great if you can provide more information on the issue, such as what is your steps to recreate this issue? any error information when it cannot be used?  Thank you.

**Comment by talobin** [comment] 2017-05-24 10:24
It's been a long time and we have not get reply back. I will go ahead and close this issue.

**Closed by talobin** 2017-05-24 10:24 UTC
