### ISSUE TITLE
当在连接飞机，拔掉USB后，app 抛出如下错误. 

### ISSUE THREAD

**Issue by karlshinetech** [dji-sdk/Mobile-SDK-Android#246] opened 2018-03-07 02:04 UTC
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
at java.lang.Thread.nativeCreate(Native Method)
at java.lang.Thread.start(Thread.java:745)
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1359)
at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:111)
at dji.midware.data.manager.P3.DataBase.submitTask(Unknown Source)
at dji.midware.data.manager.P3.DataBase.start(Unknown Source)
at dji.midware.data.model.P3.DataSmartBatteryGetPushDynamicData.start(Unknown Source)
at dji.sdksharedlib.hardware.abstractions.b.a.c.a(Unknown Source)
at dji.sdksharedlib.hardware.a.i.b(Unknown Source)
at dji.sdksharedlib.hardware.a.i.a(Unknown Source)
at dji.sdksharedlib.hardware.a.i$1.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:156)
at android.os.HandlerThread.run(HandlerThread.java:61)
我想知道这个问题导致的原因是什么,我怎么做才能避免这个问题的出现

**Comment by Michael-DJI** [comment] 2018-03-07 06:17
pls provide more details, device, drone, how to reproduce it etc.

**Comment by Djacob502** [comment] 2018-03-09 15:28
Odd how OOM error just came up. We just had a OOM error that we traced back to using the FlightControllerStateUpdate and GimbalStateUpdate at the same time in our program. After 10 minutes we noticed the GimbalStateUpdate lagged the FlightControllerStateUpdate by 3 seconds or so. Around the 15 minute mark we received the OOM error. 

To reproduce the error - start a basic program using the DJI UI library with all the widgets - start the FlightControllerStateUpdate and GimbalStateUpdate. 

Using the crystal sky 7" monitor, phantom 4 pro, m210 - with the most recent firmware, latest android studio version. 

I ended up resolving this error by not using the FlightControllerStateUpdates and GimbalStateUpdates and instead switched to using the key component method.

**Comment by Michael-DJI** [comment] 2018-03-14 15:12
@Djacob502 I tested with our UILib sample, but can't reproduce it, could u pls provide a gitHub sample with this issue?

**Comment by dingydandy** [comment] 2018-03-27 02:25
I tried on different devices, only on Huawei M3 青春版 tablet will reproduce it, on vivo phone, xiaomi phone, huawei phone don't occur, Please check it, I wonder it may related to the os.

**Comment by Michael-DJI** [comment] 2018-03-29 08:47
@dingydandy ok, thanks we will try with that tablet!

**Comment by dingydandy** [comment] 2018-04-03 02:37
@Michael-DJI 非常感谢，目前我使用的sdk是android mobile sdk 4.4.1，移动设备是华为M3青春版平板，EMUI是5.1，android系统是7.0。另外，如果想使用sample code复现的话，必须有live view图像才可以。

**Comment by dingydandy** [comment] 2018-04-03 02:49
@Michael-DJI 另外我还想顺带提两个bug
第一个问题同样是只会在华为M3青春版平板才会出现，用vivo手机试了没有问题。连接飞机时，会弹出来一些选项，即提示选择用哪个app连接飞机。如果我在做出选择的时候，选择了“始终”而不是“仅此一次”，那么app就再也连不上飞机了，除非在设置中清楚默认设置、并重启平板。
第二个问题，我在github提过（#256），论坛上问过，都没有得到回复，通过邮件（dev@dji.com）也没有解决。android mobile sdk与onboard sdk通信的时候，onboard sdk可以收到mobile sdk的消息，但是mobile sdk收不到onboard sdk的消息。相对应的版本，android mobile sdk是4.4.1，onboard sdk是3.6，A3是1.7.1.5。这个问题在华为M3青春版平板和vivo手机上都复现了，我想应该是有普遍性的。希望可以帮忙看一下，非常感谢。

**Comment by Michael-DJI** [comment] 2018-12-13 11:04
Hi, did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Closed by Michael-DJI** 2018-12-13 11:04 UTC
