### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by jayakrishnan1236** [dji-sdk/Mobile-SDK-Android#159] opened 2017-08-31 11:41 UTC
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at dji.sdk.flightcontroller.FlyZoneManager.newSendFlyForbidDataToMc(Unknown Source)
       at dji.sdk.flightcontroller.FlyZoneManager.access$1500(Unknown Source)
       at dji.sdk.flightcontroller.FlyZoneManager$7.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:818)

Drone : Phantom 4 pro
Device : Samsung J7 Prime
Dji-Sdk Version :  4.2.1

**Comment by GIS-HowardZhang** [comment] 2017-09-13 07:00
hi, I got similar Exception about DJI FlyForbid like you. 

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at dji.midware.data.forbid.db.FlyfrbPolygonMainDbManager.getDb(Unknown Source)
    at dji.midware.data.forbid.db.FlyfrbBaseDbManager.findAll(Unknown Source)
    at dji.internal.geofeature.flyforbid.FlyfrbPolygonDataUpdateManager.<init>(Unknown Source)
    at dji.internal.geofeature.flyforbid.FlyforbidUpdateService$1.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:776)

**Comment by oliverou** [comment] 2017-09-20 03:42
Hi @jayakrishnan1236 , @GIS-HowardZhang , thanks for your feedbacks! We have addressed this issue and will fix it in our upcoming SDK release.

**Comment by oliverou** [comment] 2017-09-20 04:20
Hi @jayakrishnan1236 , @GIS-HowardZhang we have just release the Android SDK 4.3, please update it and try if the issue is fixed.

**Comment by talobin** [comment] 2017-10-18 01:18
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Closed by talobin** 2017-10-18 01:18 UTC
