### ISSUE TITLE
Load of libSDKRelativeJNI.so fails at startup

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#72] opened 2017-02-16 20:53 UTC
Android 5.0.1 on Asus Tablet
SDK 3.5.1
Phantom 3 Pro. running the latest firmware (not connected at startup)
Android studio 2.2.3

Everytime i start the application i got this error message in my log:

D/houdini: [19399] Added shared library /data/app/de.xxxxx.dbg-2/lib/arm/libSDKRelativeJNI.so for ClassLoader by Native Bridge.
02-16 21:34:53.991 19313-19399/de.xxxxx.dbg W/System.err: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/de.xxxxx.dbg-2/lib/arm/libSDKRelativeJNI.so"
02-16 21:34:53.991 19313-19399/de.xxxxx.dbg W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:371)
02-16 21:34:53.991 19313-19399/de.xxxxx.dbg W/System.err:     at java.lang.System.loadLibrary(System.java:989)
02-16 21:34:53.991 19313-19399/de.xxxxx.dbg W/System.err:     at dji.midware.natives.SDKRelativeJNI.<clinit>(Unknown Source)
02-16 21:34:53.991 19313-19399/de.xxxxx.dbg W/System.err:     at dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString(Native Method)
02-16 21:34:53.991 19313-19399/de.xxxxx.dbg W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source)
02-16 21:34:53.991 19313-19399/de.xxxxx.dbg W/System.err:     at de.xxxxx.model.dji.DJIProductManager$1.run(DJIProductManager.java:92)
02-16 21:34:53.991 19313-19399/de.xxxxx.dbg W/System.err:     at java.lang.Thread.run(Thread.java:818)
02-16 21:34:53.991 19313-19399/de.xxxxx.dbg D/SDKRelativeJNI: Couldn't load lib

Nothing matter the app is more or less working, except some bugs, but this exception looks not as by purpose for me.

Can you give me an hint what could be the problem?

Regards
Maestro

**Comment by GitPlz** [comment] 2017-02-23 15:50
I get the same message, except my application will no longer run. Further down my log I have:

02-23 10:33:47.257 19254-19305/com.xxxxxx.matricecontroller E/AndroidRuntime: FATAL EXCEPTION: Thread-1169
		Process: com.xxxxxx.matricecontroller, PID: 19254
		java.lang.NoClassDefFoundError: Failed resolution of: Ldji/midware/R$raw;
			at dji.midware.data.manager.P3.h.run(Unknown Source)
			at java.lang.Thread.run(Thread.java:818)
		 Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.midware.R$raw" on path: DexPathList[[zip file "/system/framework/com.android.future.usb.accessory.jar", zip file "/data/app/com.xxxxxx.matricecontroller-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxxxxx.matricecontroller-1/lib/arm, /vendor/lib, /system/lib]]
			at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
			at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
			at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
			at dji.midware.data.manager.P3.h.run(Unknown Source) 
			at java.lang.Thread.run(Thread.java:818) 
			Suppressed: java.lang.ClassNotFoundException: dji.midware.R$raw
			at java.lang.Class.classForName(Native Method)
			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
					... 3 more
		 Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by talobin** [comment] 2017-10-17 22:47
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already (x86 issue).
Please feel free to reopen if the problem still exists.
Thanks!

**Closed by talobin** 2017-10-17 22:47 UTC
