### ISSUE TITLE
More missing string resources

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#79] opened 2017-03-22 19:36 UTC
Android SDK version 3.5.1 is missing string resources of:
- dji_check_camera_sd_card_no_space_solution
- dji_check_camera_sd_card_no_space_reason

Issue experienced while using a Phantom 4 Pro
- Flight controller firmware: 07JDDC800102CP
- Remote controller firmware: 0CKJ2003Y7
- Camera firmware: 08DLDCG0020164

**Comment by jtuchek** [comment] 2017-03-22 19:42
this is missing in both english and chinese translations

**Comment by jtuchek** [comment] 2017-03-22 19:43
for what it's worth, on the same configuration above I'm receiving, literally, hundreds of diagnostic messages about encoding errors.

**Comment by kenargo** [comment] 2017-03-23 00:36
Missing strings is really a problem in the SDK and the cause of many random crashes.

 

The complete list I have for missing strings is (English and Chinese).  There are strings missing in Chinese and not English also.

 

English:

<string name="dji_check_fc_aircraft_warming_up_reason">Aircraft warming</string>
<string name="dji_check_fc_gyroscope_reason">Gyroscope error</string>
<string name="dji_check_fc_gyroscope_solution">Solution: Please restart aircraft, if the problem persists, contact DJI Support</string>
<string name="dji_check_fc_aircraft_warming_up_solution">Wait before take off</string>
<string name="dji_check_fc_compass_abnormal_reason">Compass abnormal</string>
<string name="dji_check_fc_compass_abnormal_solution">Solution: 1. Ensure there are no magnets or metal objects near the aircraft. The ground or walls may contain metal. Move away from sources of interference before attempting flight. 2. Calibrate Compass Before Takeoff.</string>
<string name="dji_check_fc_compass_need_restart_reason">Compass need restart</string>
<string name="dji_check_fc_compass_need_restart_solution">Solution: Restart aircraft</string>
<string name="dji_check_fc_imu_install_direction_error_reason">IMU error</string>
<string name="dji_check_fc_imu_install_direction_error_solution">Solution: Check IMU Installation Direction</string>
<string name="dji_check_fc_imu_interfered_reason">IMU error</string>
<string name="dji_check_fc_wrong_propeller_reason">Propeller Error</string>
<string name="dji_check_fc_imu_interfered_solution">Solution: Move away from ground magnetic interference.</string>
<string name="dji_check_fc_plain_propeller_on_plateau_solution">Do not use standard Propellers at high altitudes.</string>
<string name="dji_check_fc_plateau_propeller_on_plain_solution">Do not use Plateau Propellers at low altitudes.</string>
<string name="dji_check_camera_sd_card_no_space_solution">SD Storage Full.</string>
<string name="dji_check_camera_sd_card_no_space_reason">SD Storage Full.</string>

 

Chinese:

 

<string name="dji_check_fc_aircraft_warming_up_reason">飞行器系统预热中</string>
<string name="dji_check_fc_aircraft_warming_up_solution">请等待</string>
<string name="dji_check_fc_compass_abnormal_reason">指南针异常</string>
<string name="dji_check_fc_compass_abnormal_solution">解决方案：1. 检查飞行器周围是否有钢铁、磁铁等物质，如某些包含钢材的地面和墙壁。远离干扰源后再起飞；2. 起飞前请先校准指南针。</string>
<string name="dji_check_fc_compass_need_restart_reason">指南针错误，需要重启</string>
<string name="dji_check_fc_compass_need_restart_solution">解决方案：请重启飞行器</string>
<string name="dji_check_fc_imu_install_direction_error_reason">IMU错误</string>
<string name="dji_check_fc_imu_install_direction_error_solution">解决方案：检查IMU安装方向</string>
<string name="dji_check_fc_imu_interfered_reason">IMU异常</string>
<string name="dji_check_fc_wrong_propeller_reason">桨叶异常</string>
<string name="dji_check_fc_imu_interfered_solution">解决方案：请远离地面磁场干扰</string>
<string name="dji_check_fc_plain_propeller_on_plateau_solution">高原上请不要使用平原桨。</string>
<string name="dji_check_fc_plateau_propeller_on_plain_solution">平原上请不要使用高原桨。</string>
<string name="dji_check_air_encoder_upgrade_reason">Aircraft updating.</string>
<string name="dji_check_air_encoder_upgrade_solution">Solution: Wait for the update complete.</string>
<string name="dji_check_camera_sd_card_no_space_solution">SD 设备内存已满.</string>
<string name="dji_check_camera_sd_card_no_space_reason">SD 设备内存已满.</string>

**Comment by jtuchek** [comment] 2017-03-23 13:59
Thanks @kenargo 

This seems to be a large problem for regressions. There's not really a build in mechanism right now for detecting failures - I'd much rather receive some generic item that says "resource not found - looking for <resource_name>".

Especially if the alternative is to crash the app runtime. And it's not very nice for each independent developer to have to encounter these crashes to have somebody send them a few strings in an open issue - which may take days and force redeployments.

I provided a solution for the SDK team here, but haven't heard back about usage, I'm willing to put whatever license on it they want to get the issue fixed https://github.com/dji-sdk/Mobile-SDK-Android/issues/64

**Comment by talobin** [comment] 2017-10-17 22:56
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Closed by talobin** 2017-10-17 22:56 UTC
