### ISSUE TITLE
DJI SDK registration fails on devices with multi user enabled

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#106] opened 2017-05-05 18:01 UTC
-  Description of the issue.
Registering the SDK for use will always fail on devices that have multi user setup - not multiple Google accounts, but the system has multiple user accounts with their own app spaces (https://source.android.com/devices/tech/admin/multi-user)

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
1) Add a second user account to the device (https://support.google.com/nexus/answer/2865483?hl=en)
2) Switch to new account (only works with non-primary account)
3) Install any application using the DJI SDK
4) Open application and try to initialize/register for use
5) Close application
6) Put device in airplane mode
7) Repeat step 4
8) SDK says registration has failed.

Usually the SDK will initialize and then keep some token around internally so an internet connection isn't needed to use the products.

Trying to initialize/register as a non-primary user will *always* fail if they are not online, even if the user has previously done this within minutes.

It seems like saving the token is failing, I'm guessing this is probably due to the non-standard user space for app installs and files.

-  Crash logs (If you can find it, it would be very helpful)
N/A
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
SDK version 3.5.1
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
Phantom 4, Mavic Pro, Inspire 1.
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
7.0
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
Nexus 9
-  Android Studio version you are using (Like Android Studio 2.2, etc)
2.3.1 stable

**Comment by talobin** [comment] 2017-10-23 01:58
Hi @jtuchek ,

Thank you for the report and sorry for such a long delay in response.
We were able to reproduce this bug and one of our developers is looking into this problem.
It should be fixed with the next SDK release.

**Comment by jtuchek** [comment] 2017-10-23 15:47
Thanks @talobin

**Comment by talobin** [comment] 2017-10-26 07:43
Hi @jtuchek ,
New update: this bug has been fixed. It was due to JNI level not correctly get current private storage space of the app for second user.
Whenever new release comes out. The bug should be gone.
Thanks!

**Comment by talobin** [comment] 2018-01-11 23:46
@jtuchek This should be fixed in the 4.4.1 release.
Please check it out.
Thanks!

**Closed by talobin** 2018-01-11 23:46 UTC
