### ISSUE TITLE
IllegalBlockSizeException on startup

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#73] opened 2017-02-16 21:31 UTC
Android 5.0.1 on Asus Tablet
SDK 3.5.1
Phantom 3 Pro. running the latest firmware (not connected at startup)
Android studio 2.2.3

Everytime i start the application i got this error message in my log:

W/linker: libaesni.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
02-16 22:26:59.141 24461-26348/de.xxxxx.dbg W/System.err: javax.crypto.IllegalBlockSizeException: last block incomplete in decryption
02-16 22:26:59.141 24461-26348/de.xxxxx..dbg W/System.err:     at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:850)
02-16 22:26:59.141 24461-26348/de.xxxxx.dbg W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:1340)
02-16 22:26:59.141 24461-26348/de.xxxxx.dbg W/System.err:     at dji.midware.c.a.a.b(Unknown Source)
02-16 22:26:59.141 24461-26348/de.xxxxx.dbg W/System.err:     at dji.internal.geo.login.GeoLoginController.decryptedString(Unknown Source)
02-16 22:26:59.141 24461-26348/de.xxxxx.dbg W/System.err:     at dji.internal.geo.login.GeoLoginController.getAccountInfoFromDb(Unknown Source)
02-16 22:26:59.141 24461-26348/de.xxxxx.dbg W/System.err:     at dji.internal.geo.login.GeoLoginController.init(Unknown Source)
02-16 22:26:59.141 24461-26348/de.xxxxx.dbg W/System.err:     at dji.internal.geo.login.GeoLoginController.access$200(Unknown Source)
02-16 22:26:59.141 24461-26348/de.xxxxx.dbg W/System.err:     at dji.internal.geo.login.GeoLoginController$1.handleMessage(Unknown Source)
02-16 22:26:59.141 24461-26348/de.xxxxx.dbg W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-16 22:26:59.141 24461-26348/de.xxxxx.dbg W/System.err:     at android.os.Looper.loop(Looper.java:135)
02-16 22:26:59.141 24461-26348/de.xxxxx.dbg W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

I Don't guess that this is by purpose. 
Can you give me a hint if it's my error or it's related to sdk?

Nothing matter the app is running ;-)

Regards
Maestro

**Comment by mikepschneider** [comment] 2017-09-05 19:07
I see a similar crash on startup, only occasionally

javax.crypto.IllegalBlockSizeException: last block incomplete in decryption
W/System.err:     at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1104)
W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:2056)
W/System.err:     at dji.midware.a.a.a.b(Unknown Source)
W/System.err:     at dji.internal.useraccount.LoginVerifyController.a(Unknown Source)
W/System.err:     at dji.internal.useraccount.LoginVerifyController.g(Unknown Source)
W/System.err:     at dji.internal.useraccount.LoginVerifyController.f(Unknown Source)
W/System.err:     at dji.internal.useraccount.LoginVerifyController.b(Unknown Source)
W/System.err:     at dji.internal.useraccount.LoginVerifyController$1.handleMessage(Unknown Source)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
E/wm220: ****resetSwitchFromWifiFlag

**Comment by talobin** [comment] 2017-10-17 22:50
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Closed by talobin** 2017-10-17 22:50 UTC

**Comment by mordka** [comment] 2018-04-16 20:43
Still occurs in SDK 4.5

**Comment by mordka** [comment] 2018-04-17 12:29
Hi I'm running SDK 4.5 and during `registerApp()` I'm getting the following exception. Sometime's product registration works but when this error happens sdk is useless.
```
W/System.err: javax.crypto.IllegalBlockSizeException: last block incomplete in decryption
        at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1143)
        at javax.crypto.Cipher.doFinal(Cipher.java:1736)
        at dji.midware.a.a.a.b(Unknown Source:31)
        at dji.internal.useraccount.LoginVerifyController.a(Unknown Source:7)
        at dji.internal.useraccount.LoginVerifyController.h(Unknown Source:16)
        at dji.internal.useraccount.LoginVerifyController.g(Unknown Source:0)
        at dji.internal.useraccount.LoginVerifyController.e(Unknown Source:0)
        at dji.internal.useraccount.LoginVerifyController$2.handleMessage(Unknown Source:46)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)```

**Comment by breakline87** [comment] 2019-04-06 06:09
This still occurs even in the demo app at 4.9.... Why was this closed without any comment on what the cause was?

**Comment by Michael-DJI** [comment] 2019-04-08 02:47
@breakline87 we have fix the issue, could you please attach your stack info?

**Comment by breakline87** [comment] 2019-04-18 09:47
2019-04-18 11:47:16.732 26784-26822/com.dji.GSDemo.GoogleMap W/System.err: javax.crypto.IllegalBlockSizeException: last block incomplete in decryption
2019-04-18 11:47:16.732 26784-26822/com.dji.GSDemo.GoogleMap W/System.err:     at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1143)
2019-04-18 11:47:16.732 26784-26822/com.dji.GSDemo.GoogleMap W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:1736)
2019-04-18 11:47:16.732 26784-26822/com.dji.GSDemo.GoogleMap W/System.err:     at dji.midware.a.a.a.b(Unknown Source:31)
2019-04-18 11:47:16.732 26784-26822/com.dji.GSDemo.GoogleMap W/System.err:     at dji.internal.useraccount.a.a(Unknown Source:7)
2019-04-18 11:47:16.732 26784-26822/com.dji.GSDemo.GoogleMap W/System.err:     at dji.internal.useraccount.a.g(Unknown Source:16)
2019-04-18 11:47:16.732 26784-26822/com.dji.GSDemo.GoogleMap W/System.err:     at dji.internal.useraccount.a.a(Unknown Source:0)
2019-04-18 11:47:16.732 26784-26822/com.dji.GSDemo.GoogleMap W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source:87)
2019-04-18 11:47:16.733 26784-26822/com.dji.GSDemo.GoogleMap W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source:129)
2019-04-18 11:47:16.733 26784-26822/com.dji.GSDemo.GoogleMap W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.access$1200(Unknown Source:0)
2019-04-18 11:47:16.733 26784-26822/com.dji.GSDemo.GoogleMap W/System.err:     at dji.sdk.sdkmanager.DJISDKManager$5.run(Unknown Source:104)
2019-04-18 11:47:16.733 26784-26822/com.dji.GSDemo.GoogleMap W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by david-kuehn** [comment] 2019-08-05 15:33
@breakline87 did you ever find a workaround for this issue by chance?

**Comment by breakline87** [comment] 2019-08-05 20:17
> @breakline87 did you ever find a workaround for this issue by chance?

No, but it does not seem to causes issues.. At least not ones I see. But literally nobody reacts here anymore... I have opened several issues, had no answer whatsoever. SDK is full of bugs and weird behaviour. Things stop working for no reason, no errors etc. DJI gives you support for $400 per issue... Worst support I've ever seen.

**Comment by david-kuehn** [comment] 2019-08-05 20:24
@breakline87 alright, no problem. I was able to ignore it and everything still seems to work fine, just as you said. Thanks!

**Comment by neilyoung** [comment] 2019-08-05 21:31
@breakline87 So true...
