### ISSUE TITLE
Sample-app crashes on Mini2 when trying the livestream feature

### ISSUE THREAD

**Issue by frippe75** [dji-sdk/Mobile-SDK-Android#1086] opened 2022-01-06 14:22 UTC
Hardware-wise everything is updated to latest.
On Mobile-SDK-Android 4.16
Stream server is running under Docker on same localnetwork.
Used the Fly app to verify it can stream as expected.

# Set my key and url here
private String liveShowUrl = "rtmp://192.168.0.93:1935/live";
private static final String URL_KEY = "******";

```
D/BufferPoolAccessor2.0: bufferpool2 0xb400007927fcfbf8 : 5(66355200 size) total buffers - 4(53084160 size) used buffers - 152/157 (recycle/alloc) - 5/154 (fetch/transfer)
I/ViewRootImpl@ce50ede[MainActivity]: ViewPostIme pointer 0
I/ViewRootImpl@ce50ede[MainActivity]: ViewPostIme pointer 1
D/Toast: show: caller = com.dji.sdk.sample.internal.utils.ToastUtils.showToast:47 
I/Toast: show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
    show: isActivityContext = false
E/AndroidRuntime: FATAL EXCEPTION: Thread-1642
    Process: com.dji.sdk.sample, PID: 11671
    java.lang.NullPointerException: Attempt to invoke virtual method 'dji.midware.media.opengl.fdd$fdd dji.midware.media.opengl.fdd.dgh(java.lang.String)' on a null object reference
        at dji.midware.media.opengl.ddf.nhf.fdd(Unknown Source:2)
        at dji.midware.media.DJIVideoDecoder.setSecondaryOutputInterval(Unknown Source:9)
        at dji.midware.media.transcode.fullframe.FullFrameHardwareTranscoder.gfd(Unknown Source:12)
        at dji.sdk.sdkmanager.LiveStreamManager.fetchSpsPps(Unknown Source:63)
        at dji.sdk.sdkmanager.LiveStreamManager.startStream(Unknown Source:94)
        at com.dji.sdk.sample.demo.camera.LiveStreamView$3.run(:331)
E/DJIUSBWifiSwitchManager: ****resetSwitchFromWifiFlag
E/DJIUsbAccessoryReceiver: receiver destroySession
D/CCodecBufferChannel: [c2.qti.avc.decoder#572] DEBUG: elapsed: n=16 [in=0 pipeline=0 out=12 smoothness=4]
D/PipelineWatcher: DEBUG: elapsed 1 / 16
I/ViewRootImpl@ce50ede[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
I/Process: Sending signal. PID: 11671 SIG: 9
Disconnected from the target VM, address: 'localhost:32775', transport: 'socket'
```

**Comment by dji-dev** [comment] 2022-01-06 14:22
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/58892'>Zendesk ticket #58892</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment] 2022-01-07 11:13
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/58892'>Zendesk ticket #58892</a>:<br><br>Dear Client
Thank you for contacting DJI.

I have reproduce your issue and I will report this to the dev team.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by frippe75** [comment] 2022-01-07 15:02
Thanks @dji-dev for that! Looking forward to a solution.

**Comment by DJI-William** [comment] 2022-02-07 04:08
This is a crash and it is fixed now, you can wait for the next MSDK 4.16.1 version release. A temp solution would be change the view from SurfaceView to TextureView will bypass this issue.

**Closed by DJI-William** 2022-02-07 04:08 UTC

**Comment by PrajwalHD58** [comment] 2022-02-10 12:57
**Hi @DJI-William / @frippe  sir, I am implementing the DJI Livestream feature Implementing live stream feature in my project, But I am unable to get a video stream on any RTMP server / VLC player, Can you help me with this?
Thanking You.**


import android.app.Activity;
import android.graphics.SurfaceTexture;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.TextureView;
import android.view.TextureView.SurfaceTextureListener;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import dji.common.error.DJIError;
import dji.common.product.Model;
import dji.common.useraccount.UserAccountState;
import dji.common.util.CommonCallbacks;
import dji.sdk.base.BaseProduct;
import dji.sdk.camera.Camera;
import dji.sdk.camera.VideoFeeder;
import dji.sdk.codec.DJICodecManager;
import dji.sdk.sdkmanager.DJISDKManager;
import dji.sdk.sdkmanager.LiveStreamManager;
import dji.sdk.useraccount.UserAccountManager;

public class MainActivity extends Activity implements SurfaceTextureListener{

    private static final String TAG = MainActivity.class.getName();
    protected VideoFeeder.VideoDataListener mReceivedVideoDataListener = null;
    // Codec for video live view
    protected DJICodecManager mCodecManager = null;

    protected TextureView mVideoSurface = null;
    private EditText stream_url;
    private Button start_live_Btn;
    private TextView url_text;
    private Handler handler;
    private boolean isStraming=false;
    private String liveShowUrl="rtmp://192.168.43.0/live/mydjidrone";
    private static final String URL_KEY = "sp_stream_url";
    private LiveStreamManager.OnLiveChangeListener listener;

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        handler = new Handler();

        initUI();

        // The callback for receiving the raw H264 video data for camera live view
        mReceivedVideoDataListener = new VideoFeeder.VideoDataListener() {
            @Override
            public void onReceive(byte[] videoBuffer, int size) {
                if (mCodecManager != null) {
                    mCodecManager.sendDataToDecoder(videoBuffer, size);
                }
            }
        };
        initListener();
        setupLiveStream();
        start_live_Btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(isStraming) {
                    stopLiveShow();
                    start_live_Btn.setText("Start Stream");
                    url_text.setVisibility(View.GONE);
                    stream_url.setVisibility(View.VISIBLE);
                    isStraming=false;
                }
                else{
                    liveShowUrl=stream_url.getText().toString().trim();
                    if(!liveShowUrl.isEmpty()) {
                        stream_url.setVisibility(View.GONE);
                        url_text.setText("Stram URL is :"+liveShowUrl);
                        url_text.setVisibility(View.VISIBLE);
                        startLiveShow(liveShowUrl);
                        start_live_Btn.setText("Stop Stream");
                        stream_url.setVisibility(View.VISIBLE);
                        isStraming = true;
                    }
                    else{
                        stream_url.setError("Empty Field");
                    }
                }
            }
        });

    }

    protected void onProductChange() {
        initPreviewer();
//        loginAccount();
    }

    private void loginAccount(){

        UserAccountManager.getInstance().logIntoDJIUserAccount(this,
                new CommonCallbacks.CompletionCallbackWith<UserAccountState>() {
                    @Override
                    public void onSuccess(final UserAccountState userAccountState) {
                        Log.e(TAG, "Login Success");
                    }
                    @Override
                    public void onFailure(DJIError error) {
                        showToast("Login Error:"
                                + error.getDescription());
                    }
                });
    }

    @Override
    public void onResume() {
        Log.e(TAG, "onResume");
        super.onResume();
        initPreviewer();
        onProductChange();

        if(mVideoSurface == null) {
            Log.e(TAG, "mVideoSurface is null");
        }
    }

    @Override
    public void onPause() {
        Log.e(TAG, "onPause");
        uninitPreviewer();
        super.onPause();
    }

    @Override
    public void onStop() {
        Log.e(TAG, "onStop");
        super.onStop();
    }

    public void onReturn(View view){
        Log.e(TAG, "onReturn");
        this.finish();
    }

    @Override
    protected void onDestroy() {
        Log.e(TAG, "onDestroy");
        uninitPreviewer();
        super.onDestroy();
    }

    private void initUI() {
        // init mVideoSurface
        mVideoSurface = (TextureView)findViewById(R.id.textureView);
        start_live_Btn=(Button) findViewById(R.id.b_start_stop);
        stream_url=(EditText)findViewById(R.id.rtmp_url);
        url_text=(TextView) findViewById(R.id.rtmp_url_text);
        if (null != mVideoSurface) {
            mVideoSurface.setSurfaceTextureListener(this);
        }
    }

    private void initPreviewer() {

        BaseProduct product = FPVDemoApplication.getProductInstance();

        if (product == null || !product.isConnected()) {
            showToast(getString(R.string.disconnected));
        } else {
            if (null != mVideoSurface) {
                mVideoSurface.setSurfaceTextureListener(this);
            }
            if (!product.getModel().equals(Model.UNKNOWN_AIRCRAFT)) {
                VideoFeeder.getInstance().getPrimaryVideoFeed().addVideoDataListener(mReceivedVideoDataListener);
            }
        }
    }

    private void uninitPreviewer() {
        Camera camera = FPVDemoApplication.getCameraInstance();
        if (camera != null){
            // Reset the callback
            VideoFeeder.getInstance().getPrimaryVideoFeed().addVideoDataListener(null);
        }
    }

    @Override
    public void onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height) {
        Log.e(TAG, "onSurfaceTextureAvailable");
        if (mCodecManager == null) {
            mCodecManager = new DJICodecManager(this, surface, width, height);
        }
    }

    @Override
    public void onSurfaceTextureSizeChanged(SurfaceTexture surface, int width, int height) {
        Log.e(TAG, "onSurfaceTextureSizeChanged");
    }

    @Override
    public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {
        Log.e(TAG,"onSurfaceTextureDestroyed");
        if (mCodecManager != null) {
            mCodecManager.cleanSurface();
            mCodecManager = null;
        }

        return false;
    }

    @Override
    public void onSurfaceTextureUpdated(SurfaceTexture surface) {
    }

    public void showToast(final String msg) {
        runOnUiThread(new Runnable() {
            public void run() {
                Toast.makeText(MainActivity.this, msg, Toast.LENGTH_SHORT).show();
            }
        });
    }

    void startLiveShow(String liveUrl) {
        showToast("Start Live Show");
        if (DJISDKManager.getInstance().getLiveStreamManager().isStreaming()) {
            showToast("already started!");
            return;
        }
        new Thread() {
            @Override
            public void run() {
                DJISDKManager.getInstance().getLiveStreamManager().setLiveUrl(liveUrl);
                int result = DJISDKManager.getInstance().getLiveStreamManager().startStream();
                DJISDKManager.getInstance().getLiveStreamManager().setStartTime();
//                getApplicationContext().getSharedPreferences(getApplicationContext().getPackageName(), Context.MODE_PRIVATE).edit().putString(URL_KEY,liveShowUrl).commit();

                showToast("startLive:" + result +
                        "\n isVideoStreamSpeedConfigurable:" + DJISDKManager.getInstance().getLiveStreamManager().isVideoStreamSpeedConfigurable() +
                        "\n isLiveAudioEnabled:" + DJISDKManager.getInstance().getLiveStreamManager().isLiveAudioEnabled());
            }
        }.start();
    }

    private void stopLiveShow() {

        DJISDKManager.getInstance().getLiveStreamManager().stopStream();
        showToast("Stop Live Show");
    }
    private void setupLiveStream() {
        DJISDKManager.getInstance().getLiveStreamManager().registerListener(listener);
        initListener();
        DJISDKManager.getInstance().getLiveStreamManager().setAudioStreamingEnabled(false);
        DJISDKManager.getInstance().getLiveStreamManager().setVideoSource(LiveStreamManager.LiveStreamVideoSource.Primary);
    }

    private void initListener() {
        listener = new LiveStreamManager.OnLiveChangeListener() {
            @Override
            public void onStatusChanged(int i) {
                showToast("status changed : " + i);
            }
        };
    }
}

**Comment by DJI-William** [comment] 2022-02-11 03:51
@PrajwalHD58 What is your startLiveStream return?

**Comment by PrajwalHD58** [comment] 2022-02-11 05:36
**@DJI-William** sir, Thanks for your reply.
The  result of startStream( int result = DJISDKManager.getInstance().getLiveStreamManager().startStream(); ) returns 254 which corresponds to the initialization error.

**Comment by DJI-William** [comment] 2022-02-11 06:33
@PrajwalHD58 You need to refer to the code here, I cannot see anything wrong in your code.
Link：https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/camera/LiveStreamView.java

**Comment by Sugar666666tang** [comment] 2022-02-11 06:34
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到。

**Comment by PrajwalHD58** [comment] 2022-02-11 06:50
@DJI-William sir,
We have built and tested the Livestream feature from [Mobile-SDK-Android](https://github.com/dji-sdk/Mobile-SDK-Android) however we are getting the same error code (254) on starting the Live stream. We are using PHANTOM 4 Pro V2 drone.

**Comment by DJI-William** [comment] 2022-02-14 09:17
Does your device has internet access?

**Comment by dji-dev** [comment] 2022-02-14 09:37
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/58892'>Zendesk ticket #58892</a>:<br><br>Dose the device refer to a PHANTOM 4 Pro V2 drone？The drone doesn't have an internet access.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment] 2022-02-14 10:45
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/58892'>Zendesk ticket #58892</a>:<br><br>If this device refers to a mobile device, yes, the device was connected to the network at the time of the test.
<br><p><em><small>°°°</small></em></p>

**Comment by killiness** [comment] 2022-03-02 01:39
我也遇到了这个问题，int result = DJISDKManager.getInstance().getLiveStreamManager().startStream();我这里返回的值是 -3，使用的M300RTK

**Comment by dji-dev** [comment] 2022-03-02 03:18
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/58892'>Zendesk ticket #58892</a>:<br><br>错误码是-3，可能是因为没有使用DJICodecManager来进行解码导致的。具体原理可以参考这两LiveStreamManager推流直播的原理是什么？篇文章：直播推流中startStream()返回的错误码是什么意思？如何使用DJICodecManager可以参考的MSDK的sample中的LiveStreamView 和VideoFeedView。
<br><p><em><small>°°°</small></em></p>
