### ISSUE TITLE
Problems initializing Android DJI SDK

### ISSUE THREAD

**Issue by mikepschneider** [dji-sdk/Mobile-SDK-Android#135] opened 2017-07-10 22:46 UTC
-  Description of the issue.

Trying to install the DJI SDK into an existing Android app.  Getting multiple errors when the app tried to register with DJI at runtime.  

-  Crash logs (If you can find it, it would be very helpful)

```
07-10 15:35:19.633 17497-17549/com.dronebase.pilotapp E/n: Failed checkIsDJIBlocked Unable to resolve host "https://api.dji-services.com/api/v1/": No address associated with hostname
```

```
07-10 15:35:19.392 17497-17531/com.dronebase.pilotapp W/System.err: java.lang.ClassNotFoundException: dji.pilot.reflect.AppPublicReflect
07-10 15:35:19.392 17497-17531/com.dronebase.pilotapp W/System.err:     at java.lang.Class.classForName(Native Method)
07-10 15:35:19.392 17497-17531/com.dronebase.pilotapp W/System.err:     at java.lang.Class.forName(Class.java:400)
07-10 15:35:19.392 17497-17531/com.dronebase.pilotapp W/System.err:     at java.lang.Class.forName(Class.java:326)
07-10 15:35:19.392 17497-17531/com.dronebase.pilotapp W/System.err:     at dji.midware.data.manager.a.b.e(Unknown Source)
07-10 15:35:19.392 17497-17531/com.dronebase.pilotapp W/System.err:     at dji.midware.data.manager.a.b.f(Unknown Source)
07-10 15:35:19.392 17497-17531/com.dronebase.pilotapp W/System.err:     at dji.midware.data.manager.a.b.<init>(Unknown Source)
07-10 15:35:19.392 17497-17531/com.dronebase.pilotapp W/System.err:     at dji.midware.data.manager.a.b.<clinit>(Unknown Source)
07-10 15:35:19.392 17497-17531/com.dronebase.pilotapp W/System.err:     at dji.midware.data.manager.a.b.getInstance(Unknown Source)
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err:     at dji.midware.usbhost.P3.NativeRcController.<clinit>(Unknown Source)
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err:     at dji.midware.usbhost.P3.NativeRcController.getIsP4pPAD(Unknown Source)
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err:     at dji.midware.link.a.a(Unknown Source)
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err:     at dji.midware.link.a$1.handleMessage(Unknown Source)
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err:     at android.os.Looper.loop(Looper.java:154)
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.pilot.reflect.AppPublicReflect" on path: DexPathList[[zip file "/data/app/com.dronebase.pilotapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.dronebase.pilotapp-2/lib/arm64, /data/app/com.dronebase.pilotapp-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-10 15:35:19.393 17497-17531/com.dronebase.pilotapp W/System.err: 	... 15 more
```

```
07-10 15:35:19.837 17497-17497/com.dronebase.pilotapp D/FlyForbid: load lib success
07-10 15:35:19.838 17497-17530/com.dronebase.pilotapp W/System.err: javax.crypto.IllegalBlockSizeException: last block incomplete in decryption
07-10 15:35:19.839 17497-17530/com.dronebase.pilotapp W/System.err:     at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1104)
07-10 15:35:19.839 17497-17530/com.dronebase.pilotapp W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:2056)
07-10 15:35:19.839 17497-17530/com.dronebase.pilotapp W/System.err:     at dji.midware.a.a.a.b(Unknown Source)
07-10 15:35:19.839 17497-17530/com.dronebase.pilotapp W/System.err:     at dji.internal.useraccount.LoginVerifyController.a(Unknown Source)
07-10 15:35:19.839 17497-17530/com.dronebase.pilotapp W/System.err:     at dji.internal.useraccount.LoginVerifyController.g(Unknown Source)
07-10 15:35:19.839 17497-17530/com.dronebase.pilotapp W/System.err:     at dji.internal.useraccount.LoginVerifyController.f(Unknown Source)
07-10 15:35:19.839 17497-17530/com.dronebase.pilotapp W/System.err:     at dji.internal.useraccount.LoginVerifyController.b(Unknown Source)
07-10 15:35:19.839 17497-17530/com.dronebase.pilotapp W/System.err:     at dji.internal.useraccount.LoginVerifyController$1.handleMessage(Unknown Source)
07-10 15:35:19.839 17497-17530/com.dronebase.pilotapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-10 15:35:19.839 17497-17530/com.dronebase.pilotapp W/System.err:     at android.os.Looper.loop(Looper.java:154)
07-10 15:35:19.839 17497-17530/com.dronebase.pilotapp W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-10 15:35:19.868 17497-17502/com.dronebase.pilotapp I/art: Do partial code cache collection, code=60KB, data=46KB
07-10 15:35:19.869 17497-17502/com.dronebase.pilotapp I/art: After code cache collection, code=56KB, data=45KB
07-10 15:35:19.869 17497-17502/com.dronebase.pilotapp I/art: Increasing code cache capacity to 256KB
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err: java.io.FileNotFoundException: flysafe/flysafe_polygon_1860.db
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:347)
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:321)
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err:     at dji.midware.data.forbid.util.FlyforbidUtils.copyDatabaseFromAsset(Unknown Source)
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err:     at dji.midware.data.forbid.db.FlyfrbPolygonSubDbManager.getDb(Unknown Source)
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err:     at dji.midware.data.forbid.db.FlyfrbBaseDbManager.<init>(Unknown Source)
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err:     at dji.midware.data.forbid.db.FlyfrbPolygonSubDbManager.<init>(Unknown Source)
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err:     at dji.midware.data.forbid.db.FlyfrbPolygonSubDbManager.init(Unknown Source)
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err:     at dji.midware.data.forbid.DJIFlyForbidController.<init>(Unknown Source)
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err:     at dji.midware.data.forbid.DJIFlyForbidController.getInstance(Unknown Source)
07-10 15:35:20.015 17497-17497/com.dronebase.pilotapp W/System.err:     at dji.sdk.sdkmanager.GeoSyncFileService.init(Unknown Source)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at com.dronebase.pilotapp.MainActivity.onCreate(MainActivity.java:112)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at android.app.Activity.performCreate(Activity.java:6682)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at android.os.Looper.loop(Looper.java:154)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6121)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-10 15:35:20.016 17497-17497/com.dronebase.pilotapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-10 15:35:20.026 17497-17530/com.dronebase.pilotapp I/n: ConnectivityManager says we are online
```

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)

Just launch the app, happens at startup
AndroidManifest.xml looks like this: 

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.dronebase.pilotapp" >

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

    <uses-sdk />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />

    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-feature
        android:name="android.hardware.usb.host"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.usb.accessory"
        android:required="true" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:name="xxx">
        <activity
            android:name="xxx"
            android:screenOrientation="portrait"
            android:label="@string/app_name"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.hardware.usb.action.USB_ACCESSORY_ATTACHED" />
            </intent-filter>
            <meta-data
                android:name="android.hardware.usb.action.USB_ACCESSORY_ATTACHED"
                android:resource="@xml/accessory_filter" />
        </activity>
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version"/>
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="XXX"/>
        <meta-data
            android:name="com.dji.sdk.API_KEY"
            android:value="XXX" />
        <service android:name="dji.sdk.sdkmanager.DJIGlobalService" >
        </service>
    </application>

</manifest>
```

-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)

    minSdkVersion = 22

-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
Not even connected
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)

Android 7.2 

-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)

Pixel XL

-  Android Studio version you are using (Like Android Studio 2.2, etc)
Android Studio 3.0 Canary 3
Build #AI-171.4056697, built on May 31, 2017
JRE: 1.8.0_112-release-b736 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

**Comment by allanvilla** [comment] 2017-08-04 01:14
I am having the same problem:

 Failed checkIsDJIBlocked Unable to resolve host "https://api.dji-services.com/api/v1/": No address associated with hostname

**Comment by negativ** [comment] 2017-08-21 12:34
Same problem with my Mavic Pro: "Unable to resolve host "https://api.dji-services.com/api/v1/"

Does anyone found a solution?

**Comment by allanvilla** [comment] 2017-08-21 12:37
Hi @negativ, my problem was solved. I had misspelled the package name from the bundle identifier.

**Comment by talobin** [comment] 2017-09-06 07:39
Hi @mikepschneider, your crash seems to be from dex loading issue. 
Our SDK is quite large and if you also include other libraries it might reach 64k limit of dex file.
Please enable multidex and see if your problem still exists.
Ref: https://stackoverflow.com/questions/26609734/how-to-enable-multidexing-with-the-new-android-multidex-support-library

For all, please ignore the error about `checkIsDJIBlocked`. It is not the cause.

**Comment by mikepschneider** [comment] 2017-09-09 00:16
I thought it was gone but I am seeing this issue again.   I have multidex enabled and otherwise it works.

The error looks like this:

```
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err: java.lang.ClassNotFoundException: dji.pilot.reflect.AppPublicReflect
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at java.lang.Class.classForName(Native Method)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at java.lang.Class.forName(Class.java:400)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at java.lang.Class.forName(Class.java:326)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at dji.midware.data.manager.a.b.e(Unknown Source)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at dji.midware.data.manager.a.b.f(Unknown Source)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at dji.midware.data.manager.a.b.<init>(Unknown Source)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at dji.midware.data.manager.a.b.<clinit>(Unknown Source)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at dji.midware.data.manager.a.b.getInstance(Unknown Source)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at dji.midware.usbhost.P3.NativeRcController.<clinit>(Unknown Source)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at dji.midware.usbhost.P3.NativeRcController.getIsP4pPAD(Unknown Source)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at dji.midware.link.a.a(Unknown Source)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at dji.midware.link.a$1.handleMessage(Unknown Source)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at android.os.Looper.loop(Looper.java:154)
09-08 17:11:02.944 30318-30505/com.dronebase.pilotapp W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
09-08 17:11:02.945 30318-30505/com.dronebase.pilotapp W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.pilot.reflect.AppPublicReflect" on path: DexPathList[[zip file "/data/app/com.dronebase.pilotapp-2/base.apk", zip file "/data/app/com.dronebase.pilotapp-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.dronebase.pilotapp-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.dronebase.pilotapp-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.dronebase.pilotapp-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.dronebase.pilotapp-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.dronebase.pilotapp-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.dronebase.pilotapp-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.dronebase.pilotapp-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.dronebase.pilotapp-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.dronebase.pilotapp-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.dronebase.pilotapp-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.dronebase.pilotapp-2/lib/arm64, /data/app/com.dronebase.pilotapp-2/base.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.dronebase.pilotapp-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
09-08 17:11:02.945 30318-30505/com.dronebase.pilotapp W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-08 17:11:02.945 30318-30505/com.dronebase.pilotapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
09-08 17:11:02.945 30318-30505/com.dronebase.pilotapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-08 17:11:02.945 30318-30505/com.dronebase.pilotapp W/System.err: 	... 15 more
```

**Comment by mikepschneider** [comment] 2017-09-09 00:37
OK, this is a red herring.  The error shows up even when the connection does work.  Maybe there was wifi or internet connectivity issues that was preventing the app from connecting, but this error shows up even when the drone connects.

**Comment by dji-dev** [comment] 2017-10-06 11:31
You are right, the error is a red herring. It has been removed from SDK 4.3.2.

**Comment by talobin** [comment] 2017-10-17 17:30
@mikepschneider please help to close the issue if you don't see the error in 4.3.2 anymore.
Thanks

**Comment by talobin** [comment] 2017-10-17 23:22
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
@mikepschneider please feel free to reopen if the problem still exists.
Thanks!

**Closed by talobin** 2017-10-17 23:22 UTC

**Comment by bartpos24** [comment] 2020-11-17 20:31
Could you help me with the similar errors


E/AndroidRuntime: FATAL EXCEPTION: DJIExecutor Urgent #1
    Process: com.dji.fpvdemo, PID: 18978
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ProcessLifecycleOwner;
        at dji.sdk.sdkmanager.DJISDKManager.initParams()
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager()
        at dji.sdk.sdkmanager.DJISDKManager.registerApp()
        at dji.sdk.sdkmanager.DJISDKManager.access$700()
        at dji.sdk.sdkmanager.DJISDKManager$6$1.onDownloadSuccess()
        at dji.internal.ghu.ghu.fdd()
        at dji.sdk.sdkmanager.DJISDKManager$6.run()
        at dji.sdksharedlib.gfd.koy.run()
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.ProcessLifecycleOwner" on path: DexPathList[[zip file "/data/user/0/com.dji.fpvdemo/.cache_sdk/sdkclasses2.jar", zip file "/data/user/0/com.dji.fpvdemo/.cache_sdk/sdkclasses.jar", zip file "/system/framework/com.android.future.usb.accessory.jar", zip file "/data/app/com.dji.fpvdemo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.dji.fpvdemo-2/lib/arm64, /data/app/com.dji.fpvdemo-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at dji.sdk.sdkmanager.DJISDKManager.initParams() 
        at dji.sdk.sdkmanager.DJISDKManager.initSDKManager() 
        at dji.sdk.sdkmanager.DJISDKManager.registerApp() 
        at dji.sdk.sdkmanager.DJISDKManager.access$700() 
        at dji.sdk.sdkmanager.DJISDKManager$6$1.onDownloadSuccess() 
        at dji.internal.ghu.ghu.fdd() 
        at dji.sdk.sdkmanager.DJISDKManager$6.run() 
        at dji.sdksharedlib.gfd.koy.run() 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:760) 
E/UsbAccessoryService: final destroy() 71
E/UsbAccessoryService: final destroy() 72
E/wm220: ****resetSwitchFromWifiFlag
E/DJIUsbAccessoryReceiver: receiver destroySession
E/UsbAccessoryService: final destroy() 73
E/UsbAccessoryService: final destroy() 75
    final destroy() 76
E/DJICrashHandler: uncaughtException 3
E/com.dji.fpvdemo.ConnectionActivity: onPause
E/com.dji.fpvdemo.ConnectionActivity: onStop
    onDestroy
E/RM500 RCType: Service Not Connected
E/PM430 RCType: Service Not Connected
E/RM500 RCType: Service Not Connected
E/PM430 RCType: Service Not Connected

**Comment by isaiascardenas** [comment] 2021-03-03 01:35
@bartpos24 i had the same issue. I fixed by adding this dependencies

`dependencies {
    ...
   
   implementation "androidx.lifecycle:lifecycle-runtime:2.0.0"
   implementation "androidx.lifecycle:lifecycle-extensions:2.0.0"
   annotationProcessor "androidx.lifecycle:lifecycle-compiler:2.0.0"
}
 `

I hope it works for you.

Regards

**Comment by bcfreitas** [comment] 2021-07-17 03:19
>    implementation "androidx.lifecycle:lifecycle-runtime:2.0.0"
>    implementation "androidx.lifecycle:lifecycle-extensions:2.0.0"
>    annotationProcessor "androidx.lifecycle:lifecycle-compiler:2.0.0"

Thanks man!! Worked here!
