### ISSUE TITLE
Appbundle Support

### ISSUE THREAD

**Issue by jim-mcandrew** [dji-sdk/Mobile-SDK-Android#430] opened 2019-07-30 12:34 UTC
Building the SDK into an APK works, but if you build it into an appbundle it crashes:

`2019-07-27 07:30:56.110 478-478/? E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.dronelink.dronelink.dev, PID: 478
   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dronelink.dronelink.dev/com.dronelink.sdk.mission.DashboardActivity}: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class dji.ux.widget.FPVWidget
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3125)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3268)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1959)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7080)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
    Caused by: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class dji.ux.widget.FPVWidget
    Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class dji.ux.widget.FPVWidget
    Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Native Method)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:686)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:829)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(Unknown Source:23)
       at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source:4)
       at com.dronelink.sdk.mission.DashboardActivity.onCreate(Unknown Source:114)
       at android.app.Activity.performCreate(Activity.java:7340)
       at android.app.Activity.performCreate(Activity.java:7331)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3105)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3268)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1959)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7080)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ldji/midware/util/AutoVideoSizeCalculator;
       at dji.ux.widget.FPVWidget.initView(Unknown Source:7)
       at dji.ux.base.j.<init>(Unknown Source:3)
       at dji.ux.widget.FPVWidget.<init>(Unknown Source:0)
       at dji.ux.widget.FPVWidget.<init>(Unknown Source:1)
       at java.lang.reflect.Constructor.newInstance0(Native Method) 
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
       at android.view.LayoutInflater.createView(LayoutInflater.java:686) 
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:829) 
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:902) 
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:905) 
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:554) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:461) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:383) 
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(Unknown Source:23) 
       at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source:4) 
       at com.dronelink.sdk.mission.DashboardActivity.onCreate(Unknown Source:114) 
       at android.app.Activity.performCreate(Activity.java:7340) 
       at android.app.Activity.performCreate(Activity.java:7331) 
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275) 
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3105) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3268) 
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1959) 
       at android.os.Handler.dispatchMessage(Handler.java:106) 
       at android.os.Looper.loop(Looper.java:214) 
       at android.app.ActivityThread.main(ActivityThread.java:7080) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
2019-07-27 07:30:56.111 478-478/? E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.midware.util.AutoVideoSizeCalculator" on path: DexPathList[[zip file "/system/framework/com.android.future.usb.accessory.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/base.apk", zip file "/data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/split_config.arm64_v8a.apk", zip file "/data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/split_config.en.apk", zip file "/data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/lib/arm64, /data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/base.apk!/lib/arm64-v8a, /data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/split_config.xhdpi.apk!/lib/arm64-v8a, /system/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       	... 34 more
   	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/split_config.arm64_v8a.apk
       at dalvik.system.DexFile.openDexFileNative(Native Method)
       at dalvik.system.DexFile.openDexFile(DexFile.java:354)
       at dalvik.system.DexFile.<init>(DexFile.java:101)
       at dalvik.system.DexFile.<init>(DexFile.java:75)
       at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
       at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
       at dalvik.system.DexPathList.<init>(DexPathList.java:164)
       at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
       at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
       at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
       at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
       at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
       at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
       at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
       at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:766)
       at android.app.LoadedApk.getClassLoader(LoadedApk.java:849)
       at android.app.LoadedApk.getResources(LoadedApk.java:1100)
       at android.app.ContextImpl.createAppContext(ContextImpl.java:2563)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6130)
       at android.app.ActivityThread.access$1200(ActivityThread.java:239)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
       		... 6 more
   	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/split_config.en.apk
       at dalvik.system.DexFile.openDexFileNative(Native Method)
       at dalvik.system.DexFile.openDexFile(DexFile.java:354)
       at dalvik.system.DexFile.<init>(DexFile.java:101)
       at dalvik.system.DexFile.<init>(DexFile.java:75)
       at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
       at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
       at dalvik.system.DexPathList.<init>(DexPathList.java:164)
       at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
       at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
       at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
       at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
       at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
2019-07-27 07:30:56.112 478-478/? E/AndroidRuntime:     at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
       at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
       at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:766)
       at android.app.LoadedApk.getClassLoader(LoadedApk.java:849)
       at android.app.LoadedApk.getResources(LoadedApk.java:1100)
       at android.app.ContextImpl.createAppContext(ContextImpl.java:2563)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6130)
       at android.app.ActivityThread.access$1200(ActivityThread.java:239)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
       		... 6 more
   	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/com.dronelink.dronelink.dev-gct2uswlbCITaMgF8lLw5g==/split_config.xhdpi.apk
       at dalvik.system.DexFile.openDexFileNative(Native Method)
       at dalvik.system.DexFile.openDexFile(DexFile.java:354)
       at dalvik.system.DexFile.<init>(DexFile.java:101)
       at dalvik.system.DexFile.<init>(DexFile.java:75)
       at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
       at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
       at dalvik.system.DexPathList.<init>(DexPathList.java:164)
       at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
       at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
       at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
       at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
       at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
       at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
       at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
       at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:766)
       at android.app.LoadedApk.getClassLoader(LoadedApk.java:849)
       at android.app.LoadedApk.getResources(LoadedApk.java:1100)
       at android.app.ContextImpl.createAppContext(ContextImpl.java:2563)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6130)
       at android.app.ActivityThread.access$1200(ActivityThread.java:239)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
       		... 6 more`

**Comment by kenargo** [comment] 2019-07-30 16:57
It's a known issue,  no fix currently. 

I reported this to dji months ago,  along with some ideas on what might be the cause but they have not issued a fix to date but continue investigation. 



⁣Get BlueMail for Android ​

**Comment by dji-dev** [comment] 2019-07-30 20:32
> Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/26601'>Zendesk ticket #26601</a>:<br><br>Hi Jim - thanks for reporting this publicly and as you know and as Ken also wrote, this is being investigated by DJI SDK Android team.  We'll keep everyone updated on the progress

Thanks,

Lisa Fedane
DJI Developer Support

**Comment by igala** [comment] 2019-11-09 14:20
does anybody know if there is an update on this issue?

**Comment by kenargo** [comment] 2019-11-09 14:29
There is a fix,  in the next update. 

No release date but it's coming soon. 

⁣Get BlueMail for Android ​

**Comment by dji-dev** [comment] 2019-11-20 17:08
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/26601'>Zendesk ticket #26601</a>:<br><br>The Android Appbundle bug has been fixed with MSDK Android V4.11.1.  Please see the following links for more information:


- **Sample Code for Bundle:** https://github.com/DJI-Mobile-SDK-Tutorials/DJI-Android-SDK-Bundle-Sample

- **MSDK Release Notes:** https://developer.dji.com/mobile-sdk/downloads/

- **UXSDK Release Notes:** https://developer.dji.com/ux-sdk/

If you would like to contact DJI Developer Support to give feedback, report bugs or request a feature request please submit your entry with this form: https://formcrafts.com/a/dji-developer-feedback-en or email Dev@DJI.com


Lisa Fedane
DJI Developer Support

**Comment by Michael-DJI** [comment] 2019-11-21 11:17
fixed in 4.11.1

**Closed by Michael-DJI** 2019-11-21 11:17 UTC

**Comment by jim-mcandrew** [comment] 2019-11-26 15:42
Is it possible to use the DJI SDK in an app bundle without loading it via a dynamic feature module?

**Comment by SteveGreenley** [comment] 2019-11-27 03:10
I've been having significant problems trying to get an app bundle working with DJI SDK 4.11.1. It would be helpful if we could understand what if anything needs to be changed in one of the existing sample applications in order to build a working app bundle. The sample app linked to above (https://github.com/DJI-Mobile-SDK-Tutorials/DJI-Android-SDK-Bundle-Sample) is significantly different from the sample applications that we've worked with so far. It's a Java-Kotlin hybrid and it puts the DJI SDK into a dynamic feature module. I'd be particularly interested to know if there are special requirements for the gradle version / target SDK / min SDK, packageOptions etc. Please help. We've been delaying a release for some time waiting for SDK 4.11 and then SDK 4.11.1.

**Comment by dji-dev** [comment] 2019-12-23 18:35
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/26601'>Zendesk ticket #26601</a>:<br><br>You do not have to use the dynamic feature module and can put it in the main bundle, the same as in the previous SDK version 4.11

Lisa Fedane
DJI Developer Support

**Comment by josechagas** [comment] 2021-03-30 17:35
I am not getting a crash I am getting ANR when trying to register my app.
Is there any updates about it? August 21 is your deadline DJI, take a look at this [link](https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html)

By the way, this link says:
**From August 2021, the Google Play Console will require all new apps to:**

- **Publish with the Android App Bundle format.**

- Utilize Play Asset Delivery or Play Feature Delivery to deliver assets or features that exceed download size of 150MB. 

- Expansion files (OBBs) will no longer be supported for new apps.

- Target API level 30 (Android 11) or above and adjust for behavioral changes.


I know there is an example for this, but it is totally outdated and It is not your main tutorial but It should be because things will change at August 2021.
