### ISSUE TITLE
Custom Mission in SampleCode always stops and error occurs after TakeOffStep 

### ISSUE THREAD

**Issue by GIS-HowardZhang** [dji-sdk/Mobile-SDK-Android#92] opened 2017-04-05 10:07 UTC
The problem has been bothering me for a week since last Tuesday (2017/3/29). I don't know if it is ralated to the sdk 4.0 upgrade.  But I do spend a lot of time testing all the possibles. 

The Custom Mission only executes TakeOffStep, aircraft rises to 1.2 m, then SampleCode App stops running and force colse several seconds after the TakeOffStep is completed. So I did some tests to compare.

-Custom Mission only keeps two steps: TakeOffStep, GoHomeStep. The problem does not appear.
-Using initTestingWaypointMission instead of initMission when prepare mission, the Waypoint Mission complete perfectly without problems.
-Using the new DJI SDK 4.0 SampleCode App, in which the custom mission is updated to Timeline Event, the problem still appears.
-Change the aircraft from M100 to P4P,  problem still occurs.

**Comment by HowardZhangNGU** [comment] 2017-04-06 04:20
I seem to have found a solution to this problem in a simple but ridiculous way.  

Using DJI SDK 4.0 SampleCode - Timeline, the problem occurs when TakeOffMission is completed. But I waited about 20 seconds after double clicked the INIT button, Then I pressed the START button, every element went fine and the mission completed just as I want. 

So I began to wonder whether the missioon was STARTED while the series of elements (or steps) was still uploading.  Of course the mission would go wrong if the whole mission steps was not fully uploaded.

**Comment by DJI-RobertLiu** [comment] 2017-04-07 18:43
It is nice to see that you finally found the solution. 
1. CustomMission is fully replaced by Timeline in SDK4.0.  Here is the details on the changes about Missions: https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/docs/README-Mission.md

2. About the timeline in the Sample code, there are two known issues, please be aware to workaround by restarting the run. 
1). In the timeline running process, once there is any error, the
timeline will stop.  This is by design, so please try to clean the
data, init the timeline and run again.
2). Another known issue to us is the waypoint mission in the second
timeline run will be skipped if the waypoint mission failed for some
reason at the first timeline run.  Please try to clean the data, init,
and run the 3rd time.

**Comment by GIS-HowardZhang** [comment] 2017-04-10 05:01
Thanks for your advice.

Now I wonder if there is a callback like "DJICompletionCallback" in sdk3.5 "mMissionManager.prepareMission(...)"  , which lets me know the progress  status and mission initialization result.

**Comment by oliverou** [comment] 2017-04-11 04:23
Hi @GIS-HowardZhang , you can check the [WaypointMissionOperatorListener](http://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMissionOperator.html?search=waypointmissionoperatorlistener&i=0&#djiwaypointmissionoperator_listener_inline) API Reference to get the operator events update.

**Comment by 503151695** [comment] 2017-04-19 04:29
Maybe I have same problem in timeline mission .  I spend a lot of time testing the SDK4.0 SampleCode App Timeline Mission Control . But it doesn't work .  When I click the Init button first time , toast told this:"Home cordinates not yet set..."    The second click will be done .  TakeOffStep well done .  WaypointMission will be executed , Timeline running results show that timeline event can't be fished. The next step won't be executed .  
I only keep three steps:TakeOffStep  hotpointMission  GoHomeStep . The  hotpointMission con't be executed .  Timeline running results show that param invalid .

**Comment by GIS-HowardZhang** [comment] 2017-04-19 08:49
Hi @503151695, 

The problem about clicking INIT button twice  does exist. And I think the cause of this problem may be that the onClick() method is returned while homeLatitude and homeLongitude are still being assigned in another thread. So that the switch statement will have no chance to execute until the second time you click INIT. I still cannot find a good way to solve this.

About "hotpoint mission param invalid",  I found this problem too. But I remenber that the timeline hotmission was completed well without any error sometimes. So in my opinion, sdk4.0 is not really stable enough for developing. Now I change back to sdk3.5 and just find another way to continue my job.

**Comment by 503151695** [comment] 2017-04-20 01:48
@GIS-HowardZhang 
I think you are right about the INIT button problem .

The problem about "hotpoint mission param invalid" has been sloved . I find that it has a new commit 20 days ago.  

But The GotoAction and Waypoint Mission make timeline error .The next step won't be executed.
timeline running results show this: (textview)
  GotoAction event is ELEMENT_STARTED.
  GotoAction event is ELEMENT_FINISHED. The execution
  could not be executed.
  Timeline Event is FINISHED Failed: The
  execution could not be executed.
Does this problem appear in SDK3.5 ? I really want to use sdk4.0 for my work .

**Comment by GIS-HowardZhang** [comment] 2017-04-21 06:18
@503151695
SDK3.5 doesn't have problem like this. But it is more difficult for a beginner to handle. if you really want to use sdk4.0, I suggest you to check if the new version sdk 4.0.1 have fix the problems. And DJI just released UI Library 1.0.0 yesterday , which is really a good news for us.

**Comment by talobin** [comment] 2017-10-17 23:03
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Closed by talobin** 2017-10-17 23:03 UTC
