### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JeffreySa** [dji-sdk/Mobile-SDK-Android#27] opened 2016-04-01 17:25 UTC
I try sample code in pt3 pro and doesnt dowk, no connected

**Comment by kenargo** [comment] 2016-04-01 17:30
Can you confirm the SDK is being registered?  If SDK register isn’t successful then you will only get video, nothing more.

**Comment by JeffreySa** [comment] 2016-04-01 18:09
Yeah, I registered in http://developer.dji.com/en/user/apps/#all with Bundle IDcom.dji.sdk.sample but even can get video

**Comment by kenargo** [comment] 2016-04-01 18:13
Are you seeing the message about the USB connection?

 

If you trace initSDKManager.onProductChanged is it being called?

**Comment by JeffreySa** [comment] 2016-04-01 18:21
Message about USB connection? Where?

**Comment by kenargo** [comment] 2016-04-01 18:22
When you plug in the USB cable to your device.

 

What aircraft are you using?

**Comment by JeffreySa** [comment] 2016-04-01 18:23
I try use the example code... Compilated in android studio in a galaxy s6 android 5

**Comment by JeffreySa** [comment] 2016-04-01 18:24
Phantom 3 profes

**Comment by kenargo** [comment] 2016-04-01 18:25
OK, so you connect the remote controller to your Android, you should see a pop-up asking about USB connection permission , same as you see when using the GO app.

**Comment by JeffreySa** [comment] 2016-04-01 18:25
When connect the phone to rc dji go app say me I need a update for Battery but y put the .bin in the sdk and no happed nothing. And a exaple say only rc connected

**Comment by kenargo** [comment] 2016-04-01 18:27
Before that.  If all apps are closed and you connect the RC what happens?

**Comment by JeffreySa** [comment] 2016-04-01 18:28
The phone show me a pop-up and I select the application that I need ... In this case the example

**Comment by JeffreySa** [comment] 2016-04-01 18:29
We can talk about that for any email?

**Comment by kenargo** [comment] 2016-04-01 18:29
OK, that is good.  Next do you trace the calls I mentioned?  Do you see a connection message coming from the SDK?

**Comment by kenargo** [comment] 2016-04-01 18:30
If you trace initSDKManager.onProductChanged is it being called?

**Comment by JeffreySa** [comment] 2016-04-01 18:31
I don't see any messages

**Comment by kenargo** [comment] 2016-04-01 18:32
What about onGetRegisteredResult?

**Comment by JeffreySa** [comment] 2016-04-01 18:34
I don't modify any code line because first I want run a sample code, after that I lear about the functions and then programming.

**Comment by JeffreySa** [comment] 2016-04-01 18:37
Bue any example work for me

**Comment by kenargo** [comment] 2016-04-01 18:37
You have something like this:

 

DJISDKManager.getInstance().initSDKManager(getApplicationContext(), new DJISDKManager.DJISDKManagerCallback() {
    @Override
    public void onGetRegisteredResult(DJIError djiError) {

Add a line like this:

 

Log.d("TEST", "Registration: " + djiError.getDescription());

 

See what the output is and let me know, it will tell if you are getting registered.

 

I assume you followed the directions to create an app ID and added to your manifest?

**Comment by JeffreySa** [comment] 2016-04-01 18:43
Yeah I follow the instructions... I will add the code line in a second

**Comment by JeffreySa** [comment] 2016-04-01 18:49
I dont found this code line, sorry

**Comment by kenargo** [comment] 2016-04-01 18:50
It will be in your Application class override

**Comment by JeffreySa** [comment] 2016-04-01 18:51
Do you have any email where we can talk and send you screen captures?

**Comment by kenargo** [comment] 2016-04-01 18:54
I prefer not to give out personal email.

 

In your Android project, do you have a class that extends android.app.Application?
 
In your manifest do you have something like this?
 
<application
    android:name=".Application"
 
Where the name is the same class name as the class extending android.app.Application.

**Comment by JeffreySa** [comment] 2016-04-01 18:56
I found it

@Override
        public void onGetRegisteredResult(DJIError error) {
            if(error == DJISDKError.REGISTRATION_SUCCESS) {
                DJISDKManager.getInstance().startConnectionToProduct();
            } else {
                Handler handler = new Handler(Looper.getMainLooper());
                handler.post(new Runnable() {

                    @Override
                    public void run() {
                        Toast.makeText(getApplicationContext(),
                                R.string.sdk_registration_message,
                                                    Toast.LENGTH_LONG).show();
                    }
                });

            }
            Log.v(TAG, error.getDescription());
        }

**Comment by kenargo** [comment] 2016-04-01 18:58
Add the code I sent just under the 

 

public void onGetRegisteredResult(DJIError error) {



 

Then run your app and there should be a trace of the SDK validation output, that will tell you if you are getting SDK register

**Comment by kenargo** [comment] 2016-04-01 18:59
Also, make sure no other apps are running on device (especially the GO app) or you will not get connection.

**Comment by JeffreySa** [comment] 2016-04-01 19:00
@Override
        public void onGetRegisteredResult(DJIError error) {
            Log.d("TEST", "Registration: " + djiError.getDescription());
            if(error == DJISDKError.REGISTRATION_SUCCESS) {


and say me "cannot resolve sysmbol 'djiError'"

**Comment by kenargo** [comment] 2016-04-01 19:03
Have you programmed before or are you new at programming?

 

Change the line to match the variable name:

 

Log.d("TEST", "Registration: " + error.getDescription());

**Comment by JeffreySa** [comment] 2016-04-01 19:04
I have 3 days in the error, have so dream sorry jajajaja

**Comment by JeffreySa** [comment] 2016-04-01 19:05
Question.... Console log dont show if a connect the phone in the controll, how I can see the error?

**Comment by JeffreySa** [comment] 2016-04-01 19:08
I put it in a toast

**Comment by kenargo** [comment] 2016-04-01 19:09
That works also but sometimes Toasts can be missed.

**Comment by kenargo** [comment] 2016-04-01 19:10
You can use a Wi-Fi debugger  or maybe for you it would be better to run the app and then after a few seconds disconnect the Android from the RC and connect to the computer; logs are buffered and it will stream to PC once connection.

**Comment by JeffreySa** [comment] 2016-04-01 19:12
Api key succ. registred

**Comment by JeffreySa** [comment] 2016-04-01 19:12
but the app show a text No product connected

**Comment by kenargo** [comment] 2016-04-01 19:14
Did you add Toast in this method to check for connection:

 

@Override
public void onProductChanged(DJIBaseProduct djiBaseProduct, DJIBaseProduct djiBaseProduct1) {

**Comment by JeffreySa** [comment] 2016-04-01 19:21
Put that now

Toast.makeText(getApplicationContext(),
                    String.format("onProductChanged oldProduct:%s, newProduct:%s", oldProduct, newProduct),
                    Toast.LENGTH_LONG).show();

**Comment by JeffreySa** [comment] 2016-04-01 19:24
show me null and null in old a new product

**Comment by kenargo** [comment] 2016-04-01 19:25
You need to program so you don’t crash when getting null.

 

Did I understand correctly that you have only tried programming for 3 days?  You have not programmed before now?

**Comment by JeffreySa** [comment] 2016-04-01 19:28
nono I  programmed before but in this project, for this drone sdk i want first run a example code before understand how sdk work.... I mean, first i want see a example running in my phone and after develop my app.

**Comment by kenargo** [comment] 2016-04-01 19:30
OK, then you should understand how to program to test for null so that you can see the Toasts from the callback as they come in.  Sometimes values are null, test for null and ignore them.  If a connection is made then there will be a value.

**Comment by JeffreySa** [comment] 2016-04-01 19:43
yes I know, I imported the github repo in android studio and followed the steps in https://developer.dji.com/get-started/mobile-sdk/Run-SDK-Sample-Code/. After all I`ve tried, this sample is still not working for me. It`d be quite helpful if you provide me an execution environment, working with the current version, given the instructions provided are outdated.

**Comment by kenargo** [comment] 2016-04-01 19:52
I do not have so much time to create this for you but I’ve attached a working application override which I use to test code for DJI.  You can replace your application with it and you should see a connection unless there is something else external to your app.

 

Best of luck

**Comment by JeffreySa** [comment] 2016-04-01 20:01
Where did you attached the workaround? I downloaded this repo but this is still not working. I checked out the latest version. This project is so important.

**Comment by kenargo** [comment] 2016-04-01 20:14
https://drive.google.com/file/d/0BzUKj4iYWZNLOTlodUpWR0hWcFk/view?usp=sharing

**Comment by JeffreySa** [comment] 2016-04-03 13:47
Hi. Many days ago we talking about this issue. I want to tell you how I create my project and you please say me if I have a mistake.
First I download this repo, open my android studio 1.5.1 in my mac. After y click in open a existent project android studio and find the unzip repo. Later in developer website I create the api key and put it in the manifest and them run the app in a Samsung galaxy s6 with android 5.1... The app say me product no found, the app won't connect.
I was so specific, I hope you can help me with that. Thanks.

**Comment by SilverChangjian** [comment] 2016-04-09 09:26
Have you provide the permission to the application for getting the usb accessory?

**Comment by edancain** [comment] 2016-04-11 21:58
Kenargo, SilverChangjian. Do either of you work on the SDK team? Jeffrey Sa's issue is exactly what I am seeing. Before your next question Kenargo, yes I know very well how to program, being the CTO at a software company. We have multiple DJI products (all the Phantoms made, Matrice, S900, S1000). What I am trying to do is exactly the same as Jeffrey, evaluate the SDK. The original SDK was horrible. With the total rewrite at version 3 we thought we might try again. Please note that for the S900, S1000 and Flamewheels we have, we did not use the DJI flight computers, installing Pixhawks from 3DR as it was a good sdk. We are trying to emulate the functionality we have working with the Pixhawk with the DJI sdk.
Here's where I take exception: A sample should work. Easy to install and run. Thereby an external dev can start to get a feel for how to code with it. If, the sample does not work, and Jeffrey has to ask this many questions and still not be able to get it to work, the SDK sample and documentation is not good.
The samples have 2.4 version samples, documentation to old versions of the simulator etc etc. That doesn't help anyone here. Documentation is horribly lacking.
If either of you have the sample working, and all an external dev needs to do is change the API key to that of their own, then update the sample if you work for the team. Otherwise upload it somewhere other people that you are trying to help here could get it from.

Jeffrey, you have been very specific, I feel your pain.

**Comment by kenargo** [comment] 2016-04-11 23:01
Me, no I am not associated with DJI nor the SDK team at DJI.  I’ve learned the SDK, mainly through trial and error.

 

Have you looked at this thread and Dave’s blog?  

 

http://forum.dev.dji.com/thread-32188-1-1.html

 

Ken

**Comment by edancain** [comment] 2016-04-11 23:10
Hi Ken,
no I hadn't seen a link to Dave's blog, thanks for posting the link here, much appreciated. 
Like you, Jeffrey and I (I don't know him) are simply trying to get through the initial hurdles that shouldn't be there to learn the SDK through trial and error.
Again my thanks, look forward to reading Dave's blog.
Edan

**Comment by SilverChangjian** [comment] 2016-04-13 12:12
Thank you for your valuable feedback. We understand that it has been frustrating and we are working hard on making the experience better.  We will improve the Android Sample Code(Including Documentation) to help you get started easily. Also we are currently working on an updated Android GSDemo, it explains how to use Waypoint Missions of DJI SDK. Soon will be published.

**Comment by oliverou** [comment] 2016-04-15 03:23
Hi all, if you meet problems when using the Android Sample Code, please check the following two items:
1. Make sure your DJI Remote Controller upgrade to the latest firmware to support [AOA](https://source.android.com/devices/accessories/protocol.html)
2. Make sure you register an App Key from DJI Developer website, and enter it in your project's AndroidManifest.xml file
3. If you are using Android 6.0 Marshmallow to run the Sample Code, please make sure **targetSdkVersion** in your your project's build.gradle file is 22 or lower.

We have updated the Readme file of Android SDK Sample Github Page, please follow the process to run the sample.

Also, we provide a new tutorial to help you import the DJI Android SDK to your own Android Studio Project, please check this link: https://github.com/DJI-Mobile-SDK/Android-ImportSDKToAndroidStudio

Hope these helps!

**Comment by edancain** [comment] 2016-04-15 17:33
SilveryChangjian, oliverou, thank you both for posting.

Edan

**Comment by edancain** [comment] 2016-04-21 18:55
JefferySA. I have the sample working thanks to the wonderful help from the SDK team. Some things that I missed that I wish to share so that you can get it running also.
Firstly, when you create your app key, use the same name as the demo package "com.dji.sdk.sample". Use this api key.
Secondly, even if your mobile device doesn't support Android SDK 23, you must have it installed for a clean import of the sample. I had been using only 22, and it would fail to bring the sample in cleanly.
Ensure that the app project structure dependency includes the DJI-SDK-LIB, (within the File->Project Structure->Dependencies), otherwise click the + button to manually add it.
Once I had a successful registration (DJISampleApplication.java file =>OnGetRegisteredResult) I still did not have the sample Connecto to Product correctly. This was due to having the DJI Go app installed and having it set as the default launch application. I uninstalled DJI.Go, and the sample code connected perfectly. 
I will be reinstalling the DJI.GO app, however I will not set it as the default, therefore when a connection to the TX controller is made, I will have to chose which app to run, the DJI.GO or the Sample.

I can confirm I have the sample working with the DJI Matrice, the Phantom 4 and the Phantom 3 Professional. 

If you still need help let me know, we seem to have had the same problems and would be happy to help you resolve them to get it working.

Edan

**Comment by talobin** [comment] 2017-10-17 22:13
Will go ahead and close this issue since it has run quite long.
@JeffreySa Please help to create a separate issue if you still have problem with current version SDK 4.3.2
Thanks!

**Closed by talobin** 2017-10-17 22:13 UTC
