### ISSUE TITLE
Resource not found exceptions thrown when emitting DJIDiagnostics

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#58] opened 2016-12-05 15:46 UTC
When the SDK invokes DJIBaseProduct.onDiagnosisUpdate(...) it always crashes with a resource not found exception.

I am using v3.4 of the SDK.

```java

Exception android.content.res.Resources$NotFoundException: String resource ID #0x0
android.content.res.Resources.getText (Resources.java:299)
android.content.res.Resources.getString (Resources.java:385)
dji.midware.g.a.a ()
dji.midware.g.a.b ()
dji.sdk.util.Util.getString ()
dji.internal.c.j.a ()
dji.internal.c.g.a ()
dji.sdk.base.DJIBaseProduct$1.onDiagnosisUpdate ()
dji.internal.c.f.c ()
dji.internal.c.m.onSuccess ()
dji.midware.data.manager.P3.u.callbackSuccess ()
dji.midware.data.manager.P3.u.access$200 ()
dji.midware.data.manager.P3.w.run ()
java.lang.Thread.run (Thread.java:818)

```

**Comment by oliverou** [comment] 2016-12-06 14:23
Hi @jtuchek,  please try the latest Android SDK 3.4.1 and check if the issue still exists. 

Also, please provide the following info for us to reproduce the issue:

-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Which firmware version of the aircraft do you use?
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

**Comment by jtuchek** [comment] 2016-12-06 15:25
I don't have all of the information requested - this is sourced from our crash reporting software (I can try to log more relevant information in the future.)

Builds are generate with Android Studio v2.2 stable.

Devices are:
HTC Nexus 9 API 24
LG Nexus 5API 23
Dell Venue 8 API 22

**Comment by kenargo** [comment] 2016-12-06 19:13
I’ve seen this also and have reported it many times.

 

I have seen it with Phantom 3, 4 and Inspire 1 but most recently my projects have been on P4 and it happens randomly.

 

I’ve seen it on Samsung Tab s, Tab A, S7 Edge and NVidia K1.

 

Android Studio is up to date (2.2.2) but it’s happened randomly for some time so I don’t expect this has anything to do with the cause.

 

Likewise, I’ve seen it for many firmware versions now but I’m running latest per GO app.

 

I think what the issue is (based on the stack) would be a call like “getResources().getXXX” where the value passed in should be a resource value but is an int.
 
AKA, the call is like this:
 
                    getResources().getString(filterID);
 
but should be this:
 
                    getResources().getString(Integer.ToString(filterID));
 
I can’t say for sure but this pattern (above) is the more common cause of an exception of this type.  Maybe a code search will find it?

**Comment by JamesMastermanDev** [comment] 2016-12-07 07:04
Looks a similar issue to #49. I am seeing this on SDK 3.4.1 on any and all aircraft (Phantom 3, 4, Inspire 1, Mavic Pro and M100). With Android devices running Android 6.0.1 and 5.1.1. Mainly Samsung S7 phone and S2 8" tablet and Nexus 5 phone.

Would be great to get this resolved as it causes app crashes regularly and there is nothing I can do about it. As others have said, it happens randomly, but I see it most often when plugging in the USB cable to the Android device (drone is already powered on).

**Comment by kenargo** [comment] 2016-12-07 07:13
Same here,  most common on initial connection of USB cable. ⁣

**Comment by jtuchek** [comment] 2016-12-07 16:54
To be more specific, when using the DJI GO application - instances that would cause the diagnostics emission to fail would be:

- drone not registered
- inconsistent firmware

I don't have a clue about what else could possibly be emitted from this callback, none of the events are documented (at least that I have seen in the mobile SDK docs, I'm sure this varies based on flight controller implementations).

**Comment by jtuchek** [comment] 2016-12-07 18:22
Us as API consumers can design around this in some fashion. If invocations of diagnostic reports fail you can wrap it in a try/catch and model it as a response that could return either success or failure for multiple emissions.

It's kind of gross... but it *sometimes* provides helpful data, but for most resolutions we seem to be going to the DJI GO application for a resolution anyways.

**Comment by kenargo** [comment] 2016-12-08 02:21
Not in my case; I’ve found that none of my code is even on the call-stack so I haven’t found a way to try/catch and ignore the offender but if you find a way I’m all ears because it’s really annoying to my users!

**Comment by jtuchek** [comment] 2016-12-08 15:37
Ohhh... @kenargo it's eager, that makes sense.

@oliverou I've included a gist that may be helpful to replacing the offending code - but because the SDK isn't open source I can't make a pull request or even point out the offending piece without some sort of omission.. so based exclusively on the stack trace, I believe this should fix the issue AND provide better feedback about why something is failing 

https://gist.github.com/jtuchek/3d8ec17a26d4a3f650652542c229b04a

**Comment by talobin** [comment] 2017-10-17 22:43
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Closed by talobin** 2017-10-17 22:43 UTC
